# Ansible pipeline

trigger:
  - master

variables:
  tf_version: "0.12.26"
  tf_state_rg: "blogpost-tfstate-rg"
  tz_state_location: "uksouth"
  tf_state_sa_name: "blogposttfstatesa"
  tf_state_container_name: "tfstate"
  tf_state_tags: ("env=blogpost-terraform-devops-pipeline" "deployedBy=devops")

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: "Install Terraform $tf_version"
    inputs:
      terraformVersion: "$tf_version"

  - task: AzureCLI@2
    displayName: "Azure CLI - Get Creds"
    inputs:
      azureSubscription: "$(SUBSCRIPTION_NAME)"
      addSpnToEnvironment: true
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az group create --name $tf_state_rg --location $tz_state_location --tags "${tf_state_tags[@]}"
        az storage account create --resource-group $tf_state_rg --name $tf_state_sa_name --sku Standard_GRS --encryption-services blob --tags "${tf_state_tags[@]}"
        ACCOUNT_KEY=$(az storage account keys list --resource-group $tf_state_rg --account-name $tf_state_sa_name --query [0].value -o tsv)
        az storage container create --name $CONTAINER_NAME --account-name $STORAGE_ACCOUNT_NAME --account-key $ACCOUNT_KEY